/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as SignupRouteImport } from './routes/signup';
import { Route as LoginRouteImport } from './routes/login';
import { Route as DashboardRouteImport } from './routes/dashboard';
import { Route as AdminRouteImport } from './routes/admin';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ItemsIndexRouteImport } from './routes/items/index';
import { Route as ItemsNewRouteImport } from './routes/items/new';
import { Route as ItemsItemIdRouteImport } from './routes/items/$itemId';

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any);
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any);
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any);
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any);
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any);
const ItemsIndexRoute = ItemsIndexRouteImport.update({
  id: '/items/',
  path: '/items/',
  getParentRoute: () => rootRouteImport,
} as any);
const ItemsNewRoute = ItemsNewRouteImport.update({
  id: '/items/new',
  path: '/items/new',
  getParentRoute: () => rootRouteImport,
} as any);
const ItemsItemIdRoute = ItemsItemIdRouteImport.update({
  id: '/items/$itemId',
  path: '/items/$itemId',
  getParentRoute: () => rootRouteImport,
} as any);

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute;
  '/admin': typeof AdminRoute;
  '/dashboard': typeof DashboardRoute;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/items/$itemId': typeof ItemsItemIdRoute;
  '/items/new': typeof ItemsNewRoute;
  '/items/': typeof ItemsIndexRoute;
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute;
  '/admin': typeof AdminRoute;
  '/dashboard': typeof DashboardRoute;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/items/$itemId': typeof ItemsItemIdRoute;
  '/items/new': typeof ItemsNewRoute;
  '/items': typeof ItemsIndexRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  '/': typeof IndexRoute;
  '/admin': typeof AdminRoute;
  '/dashboard': typeof DashboardRoute;
  '/login': typeof LoginRoute;
  '/signup': typeof SignupRoute;
  '/items/$itemId': typeof ItemsItemIdRoute;
  '/items/new': typeof ItemsNewRoute;
  '/items/': typeof ItemsIndexRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/items/$itemId'
    | '/items/new'
    | '/items/';
  fileRoutesByTo: FileRoutesByTo;
  to:
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/items/$itemId'
    | '/items/new'
    | '/items';
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/dashboard'
    | '/login'
    | '/signup'
    | '/items/$itemId'
    | '/items/new'
    | '/items/';
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute;
  AdminRoute: typeof AdminRoute;
  DashboardRoute: typeof DashboardRoute;
  LoginRoute: typeof LoginRoute;
  SignupRoute: typeof SignupRoute;
  ItemsItemIdRoute: typeof ItemsItemIdRoute;
  ItemsNewRoute: typeof ItemsNewRoute;
  ItemsIndexRoute: typeof ItemsIndexRoute;
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup';
      path: '/signup';
      fullPath: '/signup';
      preLoaderRoute: typeof SignupRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/login': {
      id: '/login';
      path: '/login';
      fullPath: '/login';
      preLoaderRoute: typeof LoginRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/dashboard': {
      id: '/dashboard';
      path: '/dashboard';
      fullPath: '/dashboard';
      preLoaderRoute: typeof DashboardRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/admin': {
      id: '/admin';
      path: '/admin';
      fullPath: '/admin';
      preLoaderRoute: typeof AdminRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/': {
      id: '/';
      path: '/';
      fullPath: '/';
      preLoaderRoute: typeof IndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/items/': {
      id: '/items/';
      path: '/items';
      fullPath: '/items/';
      preLoaderRoute: typeof ItemsIndexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/items/new': {
      id: '/items/new';
      path: '/items/new';
      fullPath: '/items/new';
      preLoaderRoute: typeof ItemsNewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    '/items/$itemId': {
      id: '/items/$itemId';
      path: '/items/$itemId';
      fullPath: '/items/$itemId';
      preLoaderRoute: typeof ItemsItemIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  DashboardRoute: DashboardRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  ItemsItemIdRoute: ItemsItemIdRoute,
  ItemsNewRoute: ItemsNewRoute,
  ItemsIndexRoute: ItemsIndexRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
